version: 2

jobs:
   build:
      working_directory: ~/microservice-ref
      machine:
         enabled: true
         #timezone: America/New_York
         #java:
            #version: openjdk8
         #services:
            #- docker
      steps:
         - checkout
         - run:
            name: Build Application
            command: ./gradlew build
         - store_test_results:
            path: build/reports/tests/test
         - run:
            name: Build Docker Container
            command: docker build --rm=false -t lucksolutions/microservice-ref .
         - run:
            name: Push Docker Container
            command: |
               docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
               docker push lucksolutions/microservice-ref
            