version: '3'

services:
   app-db:
        image: mysql
        environment: 
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'appuser'
            MYSQL_PASSWORD: 'apppassword'

   microservice:
      image: lucksolutions/microservice-ref
      environment:
         SERVER_KEYSTORE: ''
         SERVER_KEYSTORE_PASSWORD_FILE: ''
         SERVER_PASSWORD_FILE: ''
         TRUST_KEYSTORE: ''
         TRUST_KEYSTORE_PASSWORD_FILE: ''
      ports: 
            - 80:8080
      