version: '3'

services:
#   app-db:
#        environment: 
#            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
#            MYSQL_DATABASE: 'app'
#            MYSQL_USER: 'appuser'
#            MYSQL_PASSWORD: 'apppassword'

   microservice:
      build:
         context: .