
#Application info endpoint (/info) configuration
info:
   app:
      name: microservice
      description:
      version: 0.1.0
      contact:
         name: Org Name
         url: https://www.example.com
         email:

#Logging Configuration
logging:
   level:
      com.lucksolutions.service: INFO
      
#Server SSL Configuration
#The keystores and passwords need to be supplied external to the application
#server:
   #ssl:
      #enabled: true
      #client-auth: need
      #key-store: classpath:certs/server.jks
      #key-store-password: secret
      #key-password: secret
      #key-alias: test
      #trust-store: classpath:certs/trust.jks
      #trust-store-password: secret