# See full list of available spring boot properties here: 
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

#Application info endpoint (/info) configuration
info:
   app:
      name: microservice
      description:
      version: 0.1.0
      contact:
         name: Org Name
         url: https://www.example.com
         email:

#Logging Configuration
logging:
   level:
      com.lucksolutions.service: INFO
      
#Database Schema Update
#liquibase:
#   changelog: db/changelog/db.changelog-master.yaml
   
# ---------- Docker Profile -------------
---
#Database Connection
spring:
   profiles: docker
   datasource:
      url: jdbc:mysql://app-db/app
      username: appuser
      password: apppassword
      driver-class-name: com.mysql.jdbc.Driver


      
      