# See full list of available spring boot properties here: 
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

#Application info endpoint (/info) configuration
info:
   app:
      name: microservice
      description:
      version: 0.1.0
      contact:
         name: Org Name
         url: https://www.example.com
         email:

#Logging Configuration
logging:
   level:
      com.lucksolutions.service: INFO
      
#Server Configuration
server:
   port: 80
      